<?php defined( 'ABSPATH' ) || exit;

$field_login_form_styles_tab = array(
    'key'       => 'field_login_form_styles_tab',
    'label'     => __( 'Form styles', TM_LANGUAGE_DOMAIN ),
    'name'      => 'login_form_styles_tab',
    'type'      => 'tab',
    'placement' => 'left',
);

$field_login_form_width = array(
    'key'               => 'field_login_form_width',
    'label'             => esc_html__( 'Form width', TM_LANGUAGE_DOMAIN ),
    'name'              => 'tm_login_form_width',
    'aria-label'        => '',
    'type'              => 'number',
    'instructions'      => '',
    'required'          => 0,
    'conditional_logic' => 0,
    'wrapper'           => array(
        'width' => '33',
        'class' => '',
        'id'    => '',
    ),
    'default_value'     => '320',
    'min'               => '',
    'max'               => '',
    'placeholder'       => '',
    'step'              => '',
    'prepend'           => '',
    'append'            => '',
);

$field_login_form_width_unit = array(
    'key'               => 'field_login_form_width_unit',
    'label'             => esc_html__( 'Unit', TM_LANGUAGE_DOMAIN ),
    'name'              => 'tm_login_form_width_unit',
    'aria-label'        => '',
    'type'              => 'select',
    'instructions'      => '',
    'required'          => 0,
    'conditional_logic' => 0,
    'wrapper'           => array(
        'width' => '33',
        'class' => '',
        'id'    => '',
    ),
    'choices'           => array(
        '%'   => '%',
        'px'  => 'px',
        'em'  => 'em',
        'rem' => 'rem',
    ),
    'default_value'     => 'px',
    'return_format'     => 'value',
    'multiple'          => 0,
    'allow_null'        => 0,
    'ui'                => 0,
    'ajax'              => 0,
    'placeholder'       => '',
);

$field_form_background_color = array(
    'key'               => 'field_login_form_background_color',
    'label'             => esc_html__( 'Form background Color', TM_LANGUAGE_DOMAIN ),
    'name'              => 'tm_login_form_background_color',
    'aria-label'        => '',
    'type'              => 'color_picker',
    'instructions'      => '',
    'required'          => 0,
    'conditional_logic' => 0,
    'wrapper'           => array(
        'width' => '33',
        'class' => '',
        'id'    => '',
    ),
    'default_value'     => '#FFFFFF',
    'enable_opacity'    => 0,
    'return_format'     => 'string',
);

$field_login_border_width = array(
    'key'               => 'field_login_border_width',
    'label'             => esc_html__( 'Form border width', TM_LANGUAGE_DOMAIN ),
    'name'              => 'tm_login_border_width',
    'aria-label'        => '',
    'type'              => 'number',
    'instructions'      => '',
    'required'          => 0,
    'conditional_logic' => 0,
    'wrapper'           => array(
        'width' => '33',
        'class' => '',
        'id'    => '',
    ),
    'default_value'     => '1',
    'min'               => '',
    'max'               => '',
    'placeholder'       => '',
    'step'              => '',
    'prepend'           => '',
    'append'            => '',
);

$field_login_border_width_unit = array(
    'key'               => 'field_login_border_width_unit',
    'label'             => esc_html__( 'Unit', TM_LANGUAGE_DOMAIN ),
    'name'              => 'tm_login_border_width_unit',
    'aria-label'        => '',
    'type'              => 'select',
    'instructions'      => '',
    'required'          => 0,
    'conditional_logic' => 0,
    'wrapper'           => array(
        'width' => '33',
        'class' => '',
        'id'    => '',
    ),
    'choices'           => array(
        '%'   => '%',
        'px'  => 'px',
        'em'  => 'em',
        'rem' => 'rem',
    ),
    'default_value'     => 'px',
    'return_format'     => 'value',
    'multiple'          => 0,
    'allow_null'        => 0,
    'ui'                => 0,
    'ajax'              => 0,
    'placeholder'       => '',
);

$field_form_border_color = array(
    'key'               => 'field_login_border_color',
    'label'             => esc_html__( 'Form Border Color', TM_LANGUAGE_DOMAIN ),
    'name'              => 'tm_login_border_color',
    'aria-label'        => '',
    'type'              => 'color_picker',
    'instructions'      => '',
    'required'          => 0,
    'conditional_logic' => 0,
    'wrapper'           => array(
        'width' => '33',
        'class' => '',
        'id'    => '',
    ),
    'default_value'     => '#8e8e8e',
    'enable_opacity'    => 0,
    'return_format'     => 'string',
);

$field_login_form_border_radius = array(
    'key'               => 'field_login_form_border_radius',
    'label'             => esc_html__( 'Border radius', TM_LANGUAGE_DOMAIN ),
    'name'              => 'tm_login_form_border_radius',
    'aria-label'        => '',
    'type'              => 'number',
    'instructions'      => '',
    'required'          => 0,
    'conditional_logic' => 0,
    'wrapper'           => array(
        'width' => '50',
        'class' => '',
        'id'    => '',
    ),
    'default_value'     => '1',
    'min'               => '',
    'max'               => '',
    'placeholder'       => '',
    'step'              => '',
    'prepend'           => '',
    'append'            => '',
);

$field_login_form_border_radius_unit = array(
    'key'               => 'field_login_form_border_radius_unit',
    'label'             => esc_html__( 'Unit', TM_LANGUAGE_DOMAIN ),
    'name'              => 'tm_login_form_border_radius_unit',
    'aria-label'        => '',
    'type'              => 'select',
    'instructions'      => '',
    'required'          => 0,
    'conditional_logic' => 0,
    'wrapper'           => array(
        'width' => '50',
        'class' => '',
        'id'    => '',
    ),
    'choices'           => array(
        '%'   => '%',
        'px'  => 'px',
        'em'  => 'em',
        'rem' => 'rem',
    ),
    'default_value'     => 'em',
    'return_format'     => 'value',
    'multiple'          => 0,
    'allow_null'        => 0,
    'ui'                => 0,
    'ajax'              => 0,
    'placeholder'       => '',
);

$field_login_form_padding = array(
    'key'               => 'field_login_form_padding',
    'label'             => esc_html__( 'Form padding', TM_LANGUAGE_DOMAIN ),
    'name'              => 'tm_login_form_padding',
    'aria-label'        => '',
    'type'              => 'number',
    'instructions'      => '',
    'required'          => 0,
    'conditional_logic' => 0,
    'wrapper'           => array(
        'width' => '50',
        'class' => '',
        'id'    => '',
    ),
    'default_value'     => '3',
    'min'               => '',
    'max'               => '',
    'placeholder'       => '',
    'step'              => '',
    'prepend'           => '',
    'append'            => '',
);

$field_login_form_padding_unit = array(
    'key'               => 'field_login_form_padding_unit',
    'label'             => esc_html__( 'Unit', TM_LANGUAGE_DOMAIN ),
    'name'              => 'tm_login_form_padding_unit',
    'aria-label'        => '',
    'type'              => 'select',
    'instructions'      => '',
    'required'          => 0,
    'conditional_logic' => 0,
    'wrapper'           => array(
        'width' => '50',
        'class' => '',
        'id'    => '',
    ),
    'choices'           => array(
        '%'   => '%',
        'px'  => 'px',
        'em'  => 'em',
        'rem' => 'rem',
    ),
    'default_value'     => 'em',
    'return_format'     => 'value',
    'multiple'          => 0,
    'allow_null'        => 0,
    'ui'                => 0,
    'ajax'              => 0,
    'placeholder'       => '',
);

$field_login_form_field_border_width = array(
    'key'               => 'field_login_form_field_border_width',
    'label'             => esc_html__( 'Field border width', TM_LANGUAGE_DOMAIN ),
    'name'              => 'tm_login_form_field_border',
    'aria-label'        => '',
    'type'              => 'number',
    'instructions'      => '',
    'required'          => 0,
    'conditional_logic' => 0,
    'wrapper'           => array(
        'width' => '33',
        'class' => '',
        'id'    => '',
    ),
    'default_value'     => '1',
    'min'               => '',
    'max'               => '',
    'placeholder'       => '',
    'step'              => '',
    'prepend'           => '',
    'append'            => '',
);

$field_login_form_field_border_unit = array(
    'key'               => 'field_login_form_field_border_unit',
    'label'             => esc_html__( 'Unit', TM_LANGUAGE_DOMAIN ),
    'name'              => 'tm_login_form_field_border_unit',
    'aria-label'        => '',
    'type'              => 'select',
    'instructions'      => '',
    'required'          => 0,
    'conditional_logic' => 0,
    'wrapper'           => array(
        'width' => '33',
        'class' => '',
        'id'    => '',
    ),
    'choices'           => array(
        '%'   => '%',
        'px'  => 'px',
        'em'  => 'em',
        'rem' => 'rem',
    ),
    'default_value'     => 'px',
    'return_format'     => 'value',
    'multiple'          => 0,
    'allow_null'        => 0,
    'ui'                => 0,
    'ajax'              => 0,
    'placeholder'       => '',
);

$field_form_field_border_color = array(
    'key'               => 'field_login_form_field_border_color',
    'label'             => esc_html__( 'Field border Color', TM_LANGUAGE_DOMAIN ),
    'name'              => 'tm_login_form_field_border_color',
    'aria-label'        => '',
    'type'              => 'color_picker',
    'instructions'      => '',
    'required'          => 0,
    'conditional_logic' => 0,
    'wrapper'           => array(
        'width' => '33',
        'class' => '',
        'id'    => '',
    ),
    'default_value'     => '#8e8e8e',
    'enable_opacity'    => 0,
    'return_format'     => 'string',
);

$field_login_form_field_border_radius = array(
    'key'               => 'field_login_form_field_border_radius',
    'label'             => esc_html__( 'Field border radius', TM_LANGUAGE_DOMAIN ),
    'name'              => 'tm_login_form_field_border_radius',
    'aria-label'        => '',
    'type'              => 'number',
    'instructions'      => '',
    'required'          => 0,
    'conditional_logic' => 0,
    'wrapper'           => array(
        'width' => '50',
        'class' => '',
        'id'    => '',
    ),
    'default_value'     => '1',
    'min'               => '',
    'max'               => '',
    'placeholder'       => '',
    'step'              => '',
    'prepend'           => '',
    'append'            => '',
);

$field_login_form_field_border_radius_unit = array(
    'key'               => 'field_login_form_field_border_radius_unit',
    'label'             => esc_html__( 'Unit', TM_LANGUAGE_DOMAIN ),
    'name'              => 'tm_login_form_field_border_radius_unit',
    'aria-label'        => '',
    'type'              => 'select',
    'instructions'      => '',
    'required'          => 0,
    'conditional_logic' => 0,
    'wrapper'           => array(
        'width' => '50',
        'class' => '',
        'id'    => '',
    ),
    'choices'           => array(
        '%'   => '%',
        'px'  => 'px',
        'em'  => 'em',
        'rem' => 'rem',
    ),
    'default_value'     => 'em',
    'return_format'     => 'value',
    'multiple'          => 0,
    'allow_null'        => 0,
    'ui'                => 0,
    'ajax'              => 0,
    'placeholder'       => '',
);

$field_login_submit_button_bg_color = array(
    'key'               => 'field_login_submit_button_bg_color',
    'label'             => esc_html__( 'Submit button background color', TM_LANGUAGE_DOMAIN ),
    'name'              => 'tm_login_submit_button_bg_color',
    'aria-label'        => '',
    'type'              => 'color_picker',
    'instructions'      => '',
    'required'          => 0,
    'conditional_logic' => 0,
    'wrapper'           => array(
        'width' => '50',
        'class' => '',
        'id'    => '',
    ),
    'default_value'     => '#00a32a',
    'enable_opacity'    => 0,
    'return_format'     => 'string',
);

$field_submit_button_text_color = array(
    'key'               => 'field_login_submit_button_text_color',
    'label'             => esc_html__( 'Submit button text color', TM_LANGUAGE_DOMAIN ),
    'name'              => 'tm_login_submit_button_text_color',
    'aria-label'        => '',
    'type'              => 'color_picker',
    'instructions'      => '',
    'required'          => 0,
    'conditional_logic' => 0,
    'wrapper'           => array(
        'width' => '50',
        'class' => '',
        'id'    => '',
    ),
    'default_value'     => '#000000',
    'enable_opacity'    => 1,
    'return_format'     => 'string',
);

$field_default_button_background_color = array(
    'key'               => 'field_login_default_button_background_color',
    'label'             => esc_html__( 'Button background color', TM_LANGUAGE_DOMAIN ),
    'name'              => 'tm_login_default_button_background_color',
    'aria-label'        => '',
    'type'              => 'color_picker',
    'instructions'      => '',
    'required'          => 0,
    'conditional_logic' => 0,
    'wrapper'           => array(
        'width' => '50',
        'class' => '',
        'id'    => '',
    ),
    'default_value'     => '#f5f5f5',
    'enable_opacity'    => 1,
    'return_format'     => 'string',
);

$field_default_button_text_color = array(
    'key'               => 'field_login_default_button_text_color',
    'label'             => esc_html__( 'Button text color', TM_LANGUAGE_DOMAIN ),
    'name'              => 'tm_login_default_button_text_color',
    'aria-label'        => '',
    'type'              => 'color_picker',
    'instructions'      => '',
    'required'          => 0,
    'conditional_logic' => 0,
    'wrapper'           => array(
        'width' => '50',
        'class' => '',
        'id'    => '',
    ),
    'default_value'     => '#000000',
    'enable_opacity'    => 1,
    'return_format'     => 'string',
);
