<?php defined('ABSPATH') || exit;

$field_login_logo_tab = array(
    'key'       => 'field_login_logo_tab',
    'label'     => __( 'Logo', TM_LANGUAGE_DOMAIN ),
    'name'      => '',
    'type'      => 'tab',
    'placement' => 'left',
);

$field_login_use_custom_logo = array(
    'key'               => 'field_login_use_custom_logo',
    'label'             => esc_html__( 'Use Custom Logo', TM_LANGUAGE_DOMAIN ),
    'name'              => 'tm_login_use_custom_logo',
    'aria-label'        => '',
    'type'              => 'true_false',
    'instructions'      => '',
    'required'          => 0,
    'conditional_logic' => 0,
    'wrapper'           => array(
        'width' => '50',
        'class' => '',
        'id'    => '',
    ),
    'message'           => '',
    'default_value'     => 0,
    'ui_on_text'        => '',
    'ui_off_text'       => '',
    'ui'                => 1,
);

$field_login_custom_logo = array(
    'key'               => 'field_login_custom_logo',
    'label'             => esc_html__( 'Custom Logo', TM_LANGUAGE_DOMAIN ),
    'name'              => 'tm_login_custom_logo',
    'aria-label'        => '',
    'type'              => 'image',
    'instructions'      => '',
    'required'          => 0,
    'conditional_logic' => array(),
    'wrapper'           => array(
        'width' => '50',
        'class' => '',
        'id'    => '',
    ),
    'return_format'     => 'url',
    'library'           => 'all',
    'min_width'         => '',
    'min_height'        => '',
    'min_size'          => '',
    'max_width'         => '',
    'max_height'        => '',
    'max_size'          => '',
    'mime_types'        => '',
    'preview_size'      => 'medium',
);

$field_login_logo_width = array(
    'key'               => 'field_login_logo_width',
    'label'             => esc_html__( 'Logo width', TM_LANGUAGE_DOMAIN ),
    'name'              => 'tm_login_logo_width',
    'aria-label'        => '',
    'type'              => 'number',
    'instructions'      => '',
    'required'          => 0,
    'conditional_logic' => 0,
    'wrapper'           => array(
        'width' => '25',
        'class' => '',
        'id'    => '',
    ),
    'default_value'     => 300,
    'min'               => '',
    'max'               => '',
    'placeholder'       => '',
    'step'              => '0.01',
    'prepend'           => '',
    'append'            => '',
);

$field_login_logo_width_unit = array(
    'key'               => 'field_login_logo_width_unit',
    'label'             => esc_html__( 'Logo width unit', TM_LANGUAGE_DOMAIN ),
    'name'              => 'tm_login_logo_width_unit',
    'aria-label'        => '',
    'type'              => 'select',
    'instructions'      => '',
    'required'          => 0,
    'conditional_logic' => 0,
    'wrapper'           => array(
        'width' => '25',
        'class' => '',
        'id'    => '',
    ),
    'choices'           => array(
        '%'   => '%',
        'px'  => 'px',
        'em'  => 'em',
        'rem' => 'rem',
        'vw'  => 'vw',
    ),
    'default_value'     => 'px',
    'return_format'     => 'value',
    'multiple'          => 0,
    'allow_null'        => 0,
    'ui'                => 0,
    'ajax'              => 0,
    'placeholder'       => '',
);

$field_login_logo_height = array(
    'key'               => 'field_login_logo_height',
    'label'             => esc_html__( 'Logo height', TM_LANGUAGE_DOMAIN ),
    'name'              => 'tm_login_logo_height',
    'aria-label'        => '',
    'type'              => 'text',
    'instructions'      => '',
    'required'          => 0,
    'conditional_logic' => 0,
    'wrapper'           => array(
        'width' => '25',
        'class' => '',
        'id'    => '',
    ),
    'default_value'     => 'auto',
    'maxlength'         => '',
    'placeholder'       => '',
    'prepend'           => '',
    'append'            => '',
);

$field_login_logo_height_unit = array(
    'key'               => 'field_login_logo_height_unit',
    'label'             => esc_html__( 'Logo height unit', TM_LANGUAGE_DOMAIN ),
    'name'              => 'tm_login_logo_height_unit',
    'aria-label'        => '',
    'type'              => 'select',
    'instructions'      => '',
    'required'          => 0,
    'conditional_logic' => 0,
    'wrapper'           => array(
        'width' => '25',
        'class' => '',
        'id'    => '',
    ),
    'choices'           => array(
        '%'   => '%',
        'px'  => 'px',
        'em'  => 'em',
        'rem' => 'rem',
        'vw'  => 'vw',
    ),
    'default_value'     => 'px',
    'return_format'     => 'value',
    'multiple'          => 0,
    'allow_null'        => 0,
    'ui'                => 0,
    'ajax'              => 0,
    'placeholder'       => '',
);
