<?php
/**
 * Generate functions for Tamarind PDFs.
 *
 * @package Tamarind_Pdfs
 */

namespace tamarind_pdfs;

defined( 'ABSPATH' ) || exit;

use Dompdf\Dompdf;
use Dompdf\Options;
use setasign\Fpdi\Tcpdf\Fpdi;

/**
 * Generate PDFs for posts.
 */
add_action( 'save_post', __NAMESPACE__ . '\save_post_pdf', 10, 1 );

/**
 * Save post id in option to generate PDFs.
 *
 * @param int $post_id Post ID.
 */
function save_post_pdf( $post_id ) 
{
    if ( get_post_type( $post_id ) !== 'post' ) {
        return;
    }
    
    $option_key   = 'generate_post_pdf';
    $existing_ids = get_option( $option_key, '' );
    
    $ids = $existing_ids ? explode( ',', $existing_ids ) : [];
    
    if ( ! in_array( $post_id, $ids ) ) {
        $ids[] = $post_id;
        update_option( $option_key, implode( ',', $ids ) );
    }
}

/**
 * Generate PDFs for post. Generate Full PDF and Free Sample PDF. Update created PDF flag.
 *
 * @param int $post_id Post ID.
 * @return bool
 */
function set_pdfs_to_post( $post_id ) {

    $post = get_post( $post_id );

	// Only set for post_type = post!
	if ( 'post' !== $post->post_type ) {
		return;
	}
		
    // Variables comunes
    $prefixName           = 'pdf-';
    $prefixFreeSampleName = 'pdf-free-';
    $filePath             = get_path_pdf( $post_id );
    $fileName             = get_filename_pdf( $post_id, $prefixName );
    $fileFreeSampleName   = get_filename_pdf( $post_id, $prefixFreeSampleName );
    $file_original        = $filePath . $fileName;
    $file_free            = $filePath . $fileFreeSampleName;
    
    // get the HTML content of the post for the full PDF.
    $html = get_html_content( $post );
    
    if ( save_full_pdf( $filePath, $fileName, $html, $post_id ) ) {
        update_field( 'post_full_pdf', str_replace( wp_upload_dir()['basedir'], wp_upload_dir()['baseurl'], $file_original ), $post_id );
        update_field( 'post_create_pdf', 1, $post_id );
    }

    // Crear FREE SAMPLE PDF a partir de las páginas del Full PDF
    if ( save_free_pdf( $file_original, $file_free ) ) {
        update_field( 'post_free_pdf', str_replace( wp_upload_dir()['basedir'], wp_upload_dir()['baseurl'], $file_free ), $post_id );
    }
    return true;
}

/**
 * Get the path to save the PDFs.
 *
 * @param int $post_id Post ID.
 * @return string
 */
function get_path_pdf ( $post_id ) {
	$filepath = wp_upload_dir()['basedir'] . '/' . get_name_dir_pdf_files() . '/' . substr($post_id, -1, 1) . substr($post_id, 0, 1) . '/';
	return $filepath;
}

/**
 * Get the filename for the PDFs.
 *
 * @param int $post_id Post ID.
 * @param string $prefixName Prefix for the filename.
 * @return string
 */
function get_filename_pdf ( $post_id, $prefixName ) {
	$filename = $prefixName . $post_id . '-' . substr($post_id, -1, 1) . substr($post_id, 0, 1) . '.pdf'; 
	return $filename;
}

/** 
 * Get the name of the directory to save the PDF files.
 * 
 * @return string
 */
function get_name_dir_pdf_files () {
    $name = 'pdfs-downloads';
    if ( function_exists( 'get_field' ) ) {
        $name = get_field( 'pdf_path_files', 'option' );
    }
    return $name;
}

function save_full_pdf ($path, $file, $contentHtml, $post_id) {

	$pathFiles = get_stylesheet_directory();
	$pathUploads = wp_upload_dir()['basedir'];

	$options = new Options(); 
	$options->set( 'isPhpEnabled', 'true' );
	$options->set( 'isHtml5ParserEnabled', 'true' ); 
	$options->set( 'isRemoteEnabled', 'true' ); 
	// $options->set('isFontSubsettingEnabled', false);

	$options->set( 'chroot', $pathFiles . '/fonts' );
	$options->set( 'fontDir',  $pathFiles . '/fonts' );
	$options->set( 'defaultFont', 'bitter' );

	$options->set( 'tempDir',  $pathUploads . '/' . get_name_dir_pdf_files() . '/tmp' );
	$options->set( 'fontCache',  $pathUploads . '/' . get_name_dir_pdf_files() . '/tmp' );

	// TODO: Comentado para optimizar. Posiblemente se pueda eliminar.
	// ini_set( "display_errors", true );
	// ini_set( "error_log", "phperr.log" );
	// ini_set( "log_errors", true );
	// error_reporting( E_ALL );

	// TODO: Comentado para optimizar. Posiblemente se pueda eliminar.
	// $_dompdf_show_warnings = true; // record warnings generated by Dompdf
	// $_dompdf_debug = true; // output frame details for every frame in the document
	// $_DOMPDF_DEBUG_TYPES = [
	// 	'page-break' => false // record information about page break determination
	// ];

	// TODO: Comentado para optimizar. Posiblemente se pueda eliminar.
	// $options->set( 'logOutputFile', $pathUploads . '/' . get_name_dir_pdf_files() . '/tmp/log.html' );
	// $options->set( 'debugPng', false );
	// $options->set( 'debugKeepTemp', false );
	// $options->set( 'debugCss', false );
	// $options->set( 'debugLayout', false );
	// $options->set( 'debugLayoutLines', false );
	// $options->set( 'debugLayoutBlocks', false );
	// $options->set( 'debugLayoutInline', false );
	// $options->set( 'debugLayoutPaddingBox', false );
	$options->set( 'renderer', 'CPDF' );

	$dompdf = new Dompdf( $options );
	$dompdf->loadHtml( $contentHtml, 'UTF-8' );
	$dompdf->setPaper( 'A4', 'portrait' );
	$dompdf->setHttpContext([
		'ssl' => [
			'verify_peer' => FALSE,
			'verify_peer_name' => FALSE,
			'allow_self_signed'=> TRUE
		]
	]);
	$dompdf->render();

	$canvas = $dompdf->getCanvas();
	$canvas->page_script( function ($pageNumber, $pageCount, $canvas, $fontMetrics ) use ( $post_id, $pathFiles ) {
		
		$text = "Page $pageNumber / $pageCount";
		$font = $fontMetrics->getFont( 'Bitter', "normal" ); 
		$pageWidth = $canvas->get_width();
		$pageHeight = $canvas->get_height();
		$size = 10;
		$width = $fontMetrics->getTextWidth( $text, $font, $size );

		switch ( $pageNumber ) {
			case 1:
				// $canvas->text($pageWidth - $width - 20, $pageHeight - 20, 'PORTADA!', $font, $size);
				break;
			case $pageCount:
                if ( function_exists( 'get_field' ) ) {
                    $imageURL = get_field( 'pdf_header_logo', 'options' );
					$imageURL = get_path_url_image( $imageURL );
                } 
                if ( ! $imageURL ) {
                    $imageURL = $pathFiles . '/images/pdf_logo.jpg';
                }
				$imgWidth = 25; 
				$imgHeight = 25;
				$canvas->image( $imageURL, 10, $pageHeight - $imgHeight - 10, $imgWidth, $imgHeight, $resolution = "normal" );

				$textFooter = '';
                if ( function_exists( 'get_field' ) ) {
                    $textFooter = get_field( 'footer_text_left_logo', 'options' );
                }
				$sizeFooter = 10;
				$font = $fontMetrics->getFont( 'Bitter', "normal" );
				$heightFooter = $fontMetrics->getFontHeight( $font, $sizeFooter );
                if ( $textFooter ) {
                    // $widthFooter = $fontMetrics->getTextWidth( $textFooter, $font, $sizeFooter );
    				$canvas->text( $imgWidth + 12, $pageHeight - 12 - ($imgHeight/2) - ($heightFooter/2), $textFooter, $font, $sizeFooter);
                }
				$canvas->text( $pageWidth - $width - 20, $pageHeight - 12 - ($imgHeight/2) - ($heightFooter/2), $text, $font, $size );
				break;
			default:
                if ( function_exists( 'get_field' ) ) {
                    $imageURL = get_field( 'pdf_header_image', 'options' );
					$imageURL = get_path_url_image( $imageURL );
                } 
                if ( ! $imageURL ) {
                    $imageURL = $pathFiles . '/images/pdf_header.jpg';
                }
				$imgWidth = 1034; 
				$imgHeight = 50;
				$canvas->image( $imageURL, 0, 0, $imgWidth, $imgHeight, $resolution = "normal" );

				$post = get_post( $post_id );
				$titlePost = $post->post_title;

				$sizeHeader = 9;
				$font = $fontMetrics->getFont( 'Bitter', "400" ); 
				$widthHeader = $fontMetrics->getTextWidth( $titlePost, $font, $sizeHeader );
				$heightFooter = $fontMetrics->getFontHeight( $font, $sizeHeader );
				$canvas->text( ($pageWidth/2) - ($widthHeader/2), 8, $titlePost, $font, $sizeHeader, $color = array(255,255,255) );

                if ( function_exists( 'get_field' ) ) {
                    $imageURL = get_field( 'pdf_header_logo', 'options' );
					$imageURL = get_path_url_image( $imageURL );
                } 
                if ( ! $imageURL ) {
                    $imageURL = $pathFiles . '/images/pdf_logo.jpg';
                }
				$imgWidth = 25; 
				$imgHeight = 25;
				$canvas->image( $imageURL, 10, $pageHeight - $imgHeight - 10, $imgWidth, $imgHeight, $resolution = "normal" );

				$textFooter = '';
                if ( function_exists( 'get_field' ) ) {
                    $textFooter = get_field( 'footer_text_left_logo', 'options' );
                }
				$sizeFooter = 10;
				$font = $fontMetrics->getFont( 'Bitter', "normal" ); 
				$heightFooter = $fontMetrics->getFontHeight( $font, $sizeFooter );
                if ( $textFooter ) {
                    // $widthFooter = $fontMetrics->getTextWidth( $textFooter, $font, $sizeFooter );
    				$canvas->text( $imgWidth + 12, $pageHeight - 12 - ($imgHeight/2) - ($heightFooter/2), $textFooter, $font, $sizeFooter);
                }
				$canvas->text( $pageWidth - $width - 20, $pageHeight - 12 - ($imgHeight/2) - ($heightFooter/2), $text, $font, $size );
				break;
		}
	});
	$output = $dompdf->output();

	if (!is_dir($path)) {
		// dir doesn't exist, make it
		mkdir($path, 0775, true);
	}
	$r = file_put_contents($path . $file, $output);
	// exit;

	if ($r) {
		return true;
	} 
	return false;
}

/**
 * Generate the HTML content for the Free PDF from the original PDF.
 *
 * @param string $file_original Path to the original PDF.
 * @param string $file_free Path to the free PDF.
 * @return bool|string
 */
function save_free_pdf ( $file_original, $file_free ) {
    // initiate FPDI
	$pdf = new Fpdi();
	$pageCount = $pdf->setSourceFile( $file_original );
	// agregar las páginas deseadas
	$pagesToAdd = [1, 2, 4, $pageCount]; 

	// array_unique para eliminar duplicados
	// array_filter para eliminar los valores que sean mayores que el número de páginas del PDF
	$pagesToAdd = array_filter(array_unique( $pagesToAdd ), fn($i) => ( $i <= $pageCount ) );
	foreach( $pagesToAdd as $page ) {
		$pdf->AddPage();
		$tplIdx = $pdf->importPage( $page );
		$pdf->useTemplate( $tplIdx );
	}
	$pdf->Output( $file_free, 'F' );
	return true;
}
